/**
 * RM2PT Generator Runtime
 * generated by RM2PT v1.3.0
 */
package com.rm2pt.generator.initialgpt;

import com.rm2pt.generator.initialgpt.AbstractREMODELUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class REMODELUiModule extends AbstractREMODELUiModule {
  public REMODELUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
