/*
 * RM2PT Generator Runtime
 * generated by RM2PT v1.3.0
 */
package com.rm2pt.generator.initialgpt;

import com.google.inject.Injector;

import com.rm2pt.generator.initialgpt.internal.RequirementmodelActivator;

import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class REMODELExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RequirementmodelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RequirementmodelActivator activator = RequirementmodelActivator.getInstance();
		return activator != null ? activator.getInjector(RequirementmodelActivator.NET_MYDREAMY_REQUIREMENTMODEL_REMODEL) : null;
	}

}	
